apiVersion: apps/v1
kind: Deployment
metadata:
  name: sap-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sap-api

  template:
    metadata:
      labels:
        app: sap-api
        try: "0"

    spec:
      hostAliases:
      - ip: 192.168.113.12
        hostnames:
        - sofi_tbr_integration_dev
      - ip: 192.168.65.3
        hostnames:
        - fvstlimsapp01t.prod.sitad.dk
      containers:
        - name: sap-api

          # Do not change the image tag in the base directory.
          # These are patched by Kustomize in the kustomization.yaml files.
          # Use the Kustomization files in the  /apps/dev/* or /apps/test/* etc directories instead.

          image: ghcr.io/ssi-dk/sap-api:v0.0.24
          command: ["/bin/sh", "-c", "/app/start.sh"]

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: sap-api-configmap
            - secretRef:
                name: sap-api-secret

          ports:
            - containerPort: 6000
              protocol: TCP

      restartPolicy: Always
