apiVersion: apps/v1
kind: Deployment
metadata:
  name: bifrost-queue-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bifrost-queue-broker

  template:
    metadata:
      labels:
        app: bifrost-queue-broker
        try: "0"

    spec:
      hostAliases:
      - ip: "192.168.113.12"
        hostnames:
        - "sofi_tbr_integration_dev"
      - ip: "192.168.65.3"
        hostnames:
        - "fvstlimsapp01t.prod.sitad.dk"
      containers:
        - name: bifrost-queue-broker

          # Do not change the image tag in the base directory.
          # These are patched by Kustomize in the kustomization.yaml files.
          # Use the Kustomization files in the  /apps/dev/* or /apps/test/* etc directories instead.

          image: ghcr.io/ssi-dk/bifrost-queue-broker:v0.3.5

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: bifrost-queue-broker-configmap
            - secretRef:
                name: bifrost-queue-broker-secret

          # Does not need to be exposed based on Docker compose config
          # ports:
          #   - containerPort: 6000
          #     protocol: TCP
          
          volumeMounts:          
          - mountPath: /app/.certs/client.key:ro
            name: tbr-client-key
            readOnly: true
          - mountPath: /app/.certs/client.pem:ro
            name: tbr-client-cert
            readOnly: true
          - mountPath: /app/.certs/SOFI_ROOT.pem:ro
            name: tbr-ca-cert
            readOnly: true

      restartPolicy: Always
      volumes:
      - name: tbr-client-key
        hostPath:
          path: /opt/sofi/secrets/certificates/tbr/client.key
          type: File 
      - name: tbr-client-cert        
        hostPath:
          path: /opt/sofi/secrets/certificates/tbr/client.pem
          type: File 
      - name: tbr-ca-cert        
        hostPath:
          path: /opt/sofi/secrets/certificates/tbr/SOFI_ROOT.pem 
          type: File 
