apiVersion: apps/v1
kind: Deployment
metadata:
  name: sap-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sap-web

  template:
    metadata:
      labels:
        app: sap-web
        try: "0"

    spec:
      containers:
        - name: sap-web
          image: ghcr.io/ssi-dk/sap-web:v0.0.24

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: sap-web-configmap

          ports:
            - containerPort: 3333
              protocol: TCP

      restartPolicy: Always
