apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: keycloak
  interval: 1h0m0s
  values:
    resourcesPreset: "none"

    # resources:
    #   requests:
    #     cpu: 100mi

    networkPolicy:
      enabled: false

    ingress:
      enabled: true
      ingressClassName: traefik
    #   hostname: keycloak.local.com
    adminIngress:
      enabled: true
      ingressClassName: traefik
      # hostname: keycloak.local.com
