apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: keycloak
  interval: 1h0m0s
  values:
    resourcesPreset: none

    networkPolicy:
      enabled: false

    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: dev2.sofi-platform.dk
      # pathType: Prefix
    adminIngress:
      enabled: true
      ingressClassName: traefik
      hostname: dev2.sofi-platform.dk
      # hostname: kcadmin.dev2.sofi-platform.dk
      # path: /
      # pathType: Prefix

    httpRelativePath: "/auth"
    extraEnvVars:
      #   - name: KC_HOSTNAME_ADMIN_URL
      #     value: "http://dev2.sofi-platform.dk/auth/admin"
      - name: KC_PROXY
        value: edge
      - name: KC_HOSTNAME_URL
        value: http://dev2.sofi-platform.dk/auth
      - name: PROXY_ADDRESS_FORWARDING
        value: true
