apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sofi
resources:
  - ../../base/rabbitmq/
  - configmap.yaml
images:
  - name: rabbitmq
    newName: rabbitmq
    newTag: "4.0.2-management"
