apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sofi
resources:
  - ../../base/sap-api/
  - configmap.yaml
images:
  - name: sap-api
    newName: sap-api
    newTag: "v0.3.6"
