apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sofi
resources:
  - ../../base/sap-api/
  - configmap.yaml
images:
  - name: ghcr.io/ssi-dk/sap-api
    newName: ghcr.io/ssi-dk/sap-api
    newTag: "v1.0.1"
