apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sofi
resources:
  - ../../base/sap-web/
  - configmap.yaml
images:
  - name: sap-web
    newName: sap-web
    newTag: "v0.3.6"
