apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sofi
resources:
  - ../../base/bifrost-queue-broker/
  - configmap.yaml
patchesStrategicMerge:
  - bifrost-queue-broker-image.yaml
