apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sofi
resources:
  - ../../base/bifrost-queue-broker/
  - configmap.yaml
images:
  - name: bifrost-queue-broker
    newName: bifrost-queue-broker
    newTag: "v0.3.6"
