apiVersion: apps/v1
kind: Deployment
metadata:
  name: bifrost-listener
spec:
  template:
    spec:
      containers:
        - name: bifrost-listener
          image: ghcr.io/ssi-dk/bifrost-listener:v0.3.4
